### ISSUE TITLE
Example how to use

### ISSUE THREAD

**Issue by timfam** [badslug/meteor-accounting#2]
An example how to format numeric field from collection will be great!
Thanks

**Comment by johnpitchko** [comment]
In your Javascript for your template (e.g. asset.js):
```
Template.asset.helpers({
  formatCurrency(value) {
    return accounting.formatMoney(value);
  },
});
```

In your template (e.g. asset.html)
```
<template name="asset">
      {{formatCurrency initialValue}}
</template>
```

**Comment by badslug** [comment]
Thanks @johnpitchko - I'll integrate into the readme.

**Comment by badslug** [comment]
Took a while but finally got around to updating the readme.
